// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uczgzjwgvlcmkhpccayo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjemd6andndmxjbWtocGNjYXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNTk3ODQsImV4cCI6MjA1NTYzNTc4NH0.-g7sUTkm3FPbhP2gfNpJRqK5JMtDjLHpVF3apkqa7qI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);